# Pythonの組み込み関数
https://docs.python.org/ja/3/library/functions.html

## 文字列の操作

### 文字列の掛け算

In [ ]:
print('a'*4)

aaaa


### エスケープ文字


In [ ]:
print('私は\'そうだね\'と言った')
print("私は'そうだね'と言った") # ダブルクオートで囲んでいる文字列内ではシングルクオートはエスケープなしで使える

# 改行
print('私は\n\'そうだね\'\nと言った')

私は'そうだね'と言った
私は'そうだね'と言った
私は
'そうだね'
と言った


### .capitalize()
* 文字列の先頭を大文字にする

In [1]:
a='apple'
print(a.capitalize())
print('banana'.capitalize())

Apple
Banana


### .upper()

* 文字列をすべて大文字にする

### .lower()

* 文字列をすべて小文字にする

In [2]:
a='apple'
a=a.upper()
print(a)
print('banana'.upper())

a=a.lower()
print(a)

APPLE
BANANA
apple


### .split()
* 文字列を指定の文字列で分割してリストに格納する


In [3]:
a='こんにちは、世界'.split('、')
print(a)
print(a[0])
print(a[1])

['こんにちは', '世界']
こんにちは
世界


### .join()
* 引数が複数の場合、文字列を指定の文字列で結合する
* 引数が一つの場合、文字列の間に指定の文字列を挿入する

In [4]:
a='abc'
print('+'.join(a))

words=['The','fox','is','cat']
one=' '.join(words)
print(one)

a+b+c
The fox is cat


### .strip()

* 文字列の最初と最後に含まれている空白を除去する

In [5]:
a='    The     '
print(a)
print(a.strip())

    The     
The


### .replace()

* 文字列を指定の文字列で置換する


In [6]:
print('apple'.replace('a','@'))

@pple


### .index()

* 文字列やリスト内に指定した要素と合致する要素がある場合、合致した最初のインデックスを返す


In [7]:
print('apple'.index('l'))
print('apple'.index('p'))

print([1,1,2,3].index(1))
print(['apple','banana'].index('banana'))

3
1
0
1


### 文字列に変数を展開する


In [8]:
a=3
b=4
print('aの値は%dです'%a)
print('aの値は%d、bの値は%dです'%(a,b)) # タプルを使うと複数展開できる

aの値は3です
aの値は3、bの値は4です


### .format()
* 文字列内の{}に変数などを展開する。書式設定もできる。

In [9]:
print('{}が{}'.format('今夜','山田'))
a=185.3
print('{0}さんの身長は{1:.1f}cm、体重は{2:.2f}kgです'.format('山田',a,98.5))

今夜が山田
山田さんの身長は185.3cm、体重は98.50kgです


### 文字列を拡張するf,r,b,uについて

#### r-strings（raw-strings）
* エスケープシークエンスを無視した文字列

In [6]:
a='aa\nbb'
print(a)
b=r'aa\nbb'
print(b)

aa
bb
aa\nbb


#### f-strings（フォーマット済み文字列リテラル）
* 文字列の中に変数を展開できる

In [10]:
a='山田'
b=30

print(f'{a}さんは{b}歳です')

山田さんは30歳です


#### b-strings（バイト列リテラル）
* str型ではなく、バイト型のインスタンスを作成する

In [13]:
a='aaa'
b=b'aaa'
print(type(a))
print(type(b))
print(a)
print(b)


<class 'str'>
<class 'bytes'>
aaa
b'aaa'


* バイト列リテラルはASCII文字しか含むことができないので、日本語を扱いたい場合はencodeが必要

In [17]:
a=b'こんにちは'

SyntaxError: bytes can only contain ASCII literal characters. (<ipython-input-17-4ade85af16dc>, line 1)

In [18]:
a='こんにちは'
print(a.encode('utf-8'))

b'\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf'


#### u-strings（Unicode-strings）
* Unicodeに変換する（Python3ではバイト列と文字列が分けられ、文字列はデフォルトでUnicodeとして扱われるため、使う必要がない）


In [23]:
a=u'こんにちは'
b='こんにちは'
print(a)
print(b)

こんにちは
こんにちは


#### f,r,b,uの組み合わせ
* 文字列を拡張するf,r,b,uは組み合わせて使用することができる

In [25]:
a='my'
b=fr'hello\n {a} world'
print(b)

hello\n my world


### .count()
* 配列の検索要素の個数を返す


In [11]:
string='fen;kanfnkfEk'
l=['d','e','e','f']
print(string.count('e'))
print(l.count('e'))

1
2


### .find()
* 文字列中の検索要素と一致した要素のインデックスを返す


In [12]:
string='fn;kanefnkfEk'
print(string.find('e'))

6


### str()
* objectをユーザーが読みやすい文字列に変換して返す


### repr()
* objectをeval()で再び元のオブジェクトに戻せる文字列に変換して返す。representationの略。

In [62]:
import datetime
from icecream import ic

today=datetime.date.today()
ic(today)
ic(type(today))
str_today=str(today)
repr_today=repr(today)
ic(type(str_today))
ic(type(repr_today))
ic(eval(repr_today))    # reprで変換した文字列はevalで元のオブジェクトに戻せる
ic(type(eval(repr_today)))
ic(eval(str_today)) # strは読みやすい形に変換されるため、元のオブジェクトに戻せないことがある

ic| today: datetime.date(2022, 2, 1)
ic| type(today): <class 'datetime.date'>
ic| type(str_today): <class 'str'>
ic| type(repr_today): <class 'str'>
ic| eval(repr_today): datetime.date(2022, 2, 1)
ic| type(eval(repr_today)): <class 'datetime.date'>


SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<string>, line 1)

### 文字列とユニコード
https://docs.python.org/ja/3/howto/unicode.html

## データ型

### ブーリアン値の足し算


In [13]:
import numpy as np

a=True
b=False
c=True
print(a+b+c)

a=np.array([1,2,1,0])
b=np.array([1,2,0,0])
print(a==b)
print(np.sum(a==b))

2
[ True  True False  True]
3


### ブーリアンによるマスク処理


In [ ]:
import numpy as np

x=np.array([0.1,-0.4,0.8])
mask=(x<=0)   #x<=0のときTrue
print('x=',x)
print('mask=',mask)
x[mask]=0   #True(x<=0)の要素に０を代入
print('x=',x)

x= [ 0.1 -0.4  0.8]
mask= [False  True False]
x= [0.1 0.  0.8]


### .isinstance()
https://docs.python.org/ja/3/library/functions.html#isinstance

* 第一引数のオブジェクトが、第二引数の型のインスタンス、またはサブクラスのインスタンスであればTrueを返す

In [14]:
class Greet:
    def hello(self):
        print('Hello')

x=Greet()
print(isinstance('string', str))
print(isinstance(x,Greet))

True
True


### .\_\_class\_\_
* オブジェクトのクラスを返す

In [15]:
import numpy as np

x=np.array([1,2,3])
print(x.__class__)
print(x.__class__.__name__)

<class 'numpy.ndarray'>
ndarray


## ラムダ式

### lambda
* 無名関数を作成する
* イテレート（繰り返し）可能な引数（リストなど）が渡された場合はすべて反復計算する（通常の関数（def）もできる）
* わざわざ関数を用意するのもめんどくさい、ちょっとした処理をする場合にささっと書ける

In [17]:
# lambdaとdefの処理を比較
import numpy as np

x=np.arange(0,10,1)

# lambdaの処理を確認
y=lambda n:2*n
print('lambda:',y(x))

# 通常の関数の処理を確認
def get_twice(x):
    return 2*x

print('def:',get_twice(x))

# ラムダ式では複数行にまたがる文を使うことはできないが、if文に相当する三項演算子は使用可能。
get_odd_even = lambda x: 'even' if x % 2 == 0 else 'odd'

print(get_odd_even(3))
print(get_odd_even(4))

lambda: [ 0  2  4  6  8 10 12 14 16 18]
def: [ 0  2  4  6  8 10 12 14 16 18]
odd
even


## リスト、タプル、辞書の操作

### タプル


In [ ]:
tpl1=('a','b')
tpl2=('a',) # タプルの要素が１つの場合は','をつける
tpl3=('a')  # これはタプルにならない（数値演算の際の（）として認識されるため）
print(tpl1,tpl2,tpl3)

('a', 'b') ('a',) a


### 辞書

In [18]:
# 辞書への追加と削除
fruits={}
fruits['apple']='red'
fruits['banana']='yellow'
print(fruits)
del fruits['apple']
print(fruits)

# 辞書にリストを登録
fruits={}
fruits['apple']=['red']
fruits['banana']=['yellow']
print(fruits)

# 辞書のリストに要素を追加
fruits['apple'].append('green')
print(fruits)

{'apple': 'red', 'banana': 'yellow'}
{'banana': 'yellow'}
{'apple': ['red'], 'banana': ['yellow']}
{'apple': ['red', 'green'], 'banana': ['yellow']}


### スライスとインデックス


In [ ]:
import numpy as np
a=np.arange(10)
print(a)
print(a[:5])
print(a[1:3])
print(a[-2])
print(a[1:8:2]) # start:stop:step
print(a[::-1])  # 反転

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[1 2]
8
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


### 多次元配列のスライスによる要素指定


In [ ]:
x=np.arange(54)
x=x.reshape([2,3,3,3])

print('x=\n',x)

print('\nx[0]=\n',x[0])
print('\nx[0,0,0]=\n',x[0,0,0])
print('\nx[0,0,0:2]=\n',x[0,0,0:2])
print('\nx[:,0,0:2:2]=\n',x[:,0,0:2:2])

x=
 [[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]

x[0]=
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

x[0,0,0]=
 [0 1 2]

x[0,0,0:2]=
 [[0 1 2]
 [3 4 5]]

x[:,0,0:2:2]=
 [[[ 0  1  2]]

 [[27 28 29]]]


### .keys()
* 辞書に含まれるすべてのキーを取得する

### .values()
* 辞書に含まれるすべての値を取得する

### .items()
* 辞書のキーと値を取得する

In [19]:
apple={'red':50,'green':100}
print(apple.keys())

for key in apple.keys():
  print(key)

apple_keys=list(apple.keys())
print(apple_keys)

print(apple.values())

for value in apple.values():
  print(value)

apple_values=list(apple.values())
print(apple_values)

for item in apple.items():
  print(item)

print(list(apple.items()))

for key,val in apple.items():
  apple[key]=val**2

print(apple)

dict_keys(['red', 'green'])
red
green
['red', 'green']
dict_values([50, 100])
50
100
[50, 100]
('red', 50)
('green', 100)
[('red', 50), ('green', 100)]
{'red': 2500, 'green': 10000}


### 辞書のリストをソートする
* 辞書のリストに関しては比較演算子がサポートされていないため、無名関数でkeyを指定する


In [20]:
import pprint
l=[{'Age':20,'Name':'Bob'},{'Age':40,'Name':'Charlie'},{'Age':30,'Name':'Alice'}]
pprint.pprint(l)
pprint.pprint(sorted(l,key=lambda x: x['Age']))
pprint.pprint(sorted(l,key=lambda x: x['Name']))
pprint.pprint(sorted(l,key=lambda x: x['Age'],reverse=True))

pprint.pprint(max(l,key=lambda x: x['Age']))
pprint.pprint(min(l,key=lambda x: x['Age']))

#辞書の各val（リスト）の最後の要素でソート（降順）
d={'result3':[7,4,5],'result2':[1,2,99],'result1':[4,5,6]}
for key,val in sorted(d.items(),key=lambda x: x[1][-1],reverse=True):
  print(str(key)+':'+str(val))

[{'Age': 20, 'Name': 'Bob'},
 {'Age': 40, 'Name': 'Charlie'},
 {'Age': 30, 'Name': 'Alice'}]
[{'Age': 20, 'Name': 'Bob'},
 {'Age': 30, 'Name': 'Alice'},
 {'Age': 40, 'Name': 'Charlie'}]
[{'Age': 30, 'Name': 'Alice'},
 {'Age': 20, 'Name': 'Bob'},
 {'Age': 40, 'Name': 'Charlie'}]
[{'Age': 40, 'Name': 'Charlie'},
 {'Age': 30, 'Name': 'Alice'},
 {'Age': 20, 'Name': 'Bob'}]
{'Age': 40, 'Name': 'Charlie'}
{'Age': 20, 'Name': 'Bob'}
result2:[1, 2, 99]
result1:[4, 5, 6]
result3:[7, 4, 5]


### .copy()
* 変数の値を新しいオブジェクトとしてコピーする（参照せずに値をコピーする）

In [22]:
val1=100
val2=val1   # 参照渡しのため、オブジェクト（変数の値）のid（参照先）は同じになる
print('val1更新前\n','id(val1)=',id(val1),'id(val2)=',id(val2))
val1=0    # 数値、文字列は再代入不可（イミュータブル）なオブジェクトなため、この時点でval1のidが変わる
print('val1=',val1,'val2=',val2)
print('val1更新後\n','id(val1)=',id(val1),'id(val2)=',id(val2))

list1=[0,10,0]
list2=list1   # 参照渡しのため、オブジェクト（変数の値）のid（参照先）は同じになる
list3=list1.copy()    # 値渡しのため、オブジェクトのidが新規作成される
print('list1更新前\n','id(list1)=',id(list1),'id(list2)=',id(list2),'id(list3)=',id(list3))

list1.append(100)   # リストは再代入可（ミュータブル）なオブジェクトなため、list1のidは変わらず、同じidのlist2も更新される
print('list1=',list1,'list2=',list2,'list3=',list3)
print('list1更新後\n','id(list1)=',id(list1),'id(list2)=',id(list2),'id(list3)=',id(list3))

val1更新前
 id(val1)= 4407694800 id(val2)= 4407694800
val1= 0 val2= 100
val1更新後
 id(val1)= 4407503120 id(val2)= 4407694800
list1更新前
 id(list1)= 4495616448 id(list2)= 4495616448 id(list3)= 4495430464
list1= [0, 10, 0, 100] list2= [0, 10, 0, 100] list3= [0, 10, 0]
list1更新後
 id(list1)= 4495616448 id(list2)= 4495616448 id(list3)= 4495430464


### .size
* 配列の全要素数を取得する

### .shape
* 配列の行数、列数をタプルとして取得する

In [23]:
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
print(a)
print(a.size)
print(a.shape)

[[1 2 3]
 [5 6 7]]
6
(2, 3)


### .append()
* リストの末尾に要素を追加する

### .pop()
* リストから指定したインデックスの要素を削除する

In [24]:
lst=['a','c','d']
lst.append('b')
print(lst)

lst.pop()
print(lst)

lst.pop(1)
print(lst)

['a', 'c', 'd', 'b']
['a', 'c', 'd']
['a', 'd']


### in 演算子


In [25]:
a=[1,2,3]
b=(1,2,3)
c={1:'apple',2:'banana',3:'grape'}
d='2時間も待たされた'

print(2 in a)
print(2 in b)
print(2 in c)
print('2' in d)

True
True
True
True


### not in 演算子

In [26]:
a=[1,2,3]
b=(1,2,3)
c={1:'apple',2:'banana',3:'grape'}
d='2時間も待たされた'

print(2 not in a)
print(2 not in b)
print(2 not in c)
print('2' not in d)

False
False
False
False


### .zip()
* それぞれのイテラブルから要素を集めたイテレータを作る(配列を返すわけではないことに注意)


In [27]:
a=[1,3,5]
b=[2,4,6]
c=[3,5,7]
d=[2,4]
zipped=zip(a,b,c,d)
print(zipped)

zipped=list(zipped)
print(zipped)

[(1, 2, 3, 2), (3, 4, 5, 4)]


### len()
* 文字列、リスト、タプルなどの要素の数を返す

In [28]:
a=[7,8,9]
b=list(range(len(a)))
print('b=',b)

b= [0, 1, 2]


### .reverse()
* 元のリストを逆順に並べ替える
* 元のリスト自体が書き換えられる破壊的処理

### .reversed()
* 要素を逆順に取り出すイテレータを返す。(リストを返すわけではない)
* 元のリストは変更されない非破壊的処理。


In [29]:
a=[1,2,3]
a.reverse()
print('a=',a)

b=[4,5,6]
c=reversed(b)
list_c=list(c)
print('b=',b)
print('c=',c)
print('list_c=',list_c)

d=[7,8,9]
for num in reversed(d):
    print(num)

a= [3, 2, 1]
b= [4, 5, 6]
c= <list_reverseiterator object at 0x10bf3ee50>
list_c= [6, 5, 4]
9
8
7


## ループ

### .range()
* 指定した範囲の、整数からなるリストを返す

In [30]:
print(list(range(0,10)))
print(list(range(0,10,3)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 3, 6, 9]


### ループの種類

In [31]:
colors=['red','blue','yellow','pink']
items={'apple':'red','banana':'yellow','peach':'pink'}

# 通常のforループ
for color in colors:    # colorには要素そのものが入る
  print(color)

# enumerate関数を使ったループ
for i ,color in enumerate(colors):    # iにはインデックス、colorには要素そのものが入る
  print('i=',i,'color=',color)

for i , item in enumerate(items):    # 辞書の場合はiがインデックス、itemにはキーが入る
  print(i,item)

# range()とlen()を使ったループ
for i in range(len(colors)):    # iにはインデックスが入る
  print('i=',i,colors[i])

red
blue
yellow
pink
i= 0 color= red
i= 1 color= blue
i= 2 color= yellow
i= 3 color= pink
0 apple
1 banana
2 peach
i= 0 red
i= 1 blue
i= 2 yellow
i= 3 pink


### break

In [32]:
colors=['red','blue','yellow','pink']

for i in range(len(colors)):
  if i==2:
    break   # この時点でループを終了
  print(colors[i])

red
blue


### continue

In [33]:
colors=['red','blue','yellow','pink']

for i in range(len(colors)):
  if i==2:
    continue    # 飛ばして次の処理をすすめる
  print(colors[i])

red
blue
pink


## 例外処理

In [ ]:
try:
  num1=float(input('数字を入力してください'))
  num2=float(input('数字を入力してください'))
  print(num1/num2)
except(ZeroDivisionError,ValueError):
  print('無効な入力です')

数字を入力してください4
数字を入力してください0
無効な入力です


## 関数

### 関数の引数にリスト、タプル、辞書を展開して渡す
https://note.nkmk.me/python-argument-expand/

In [34]:
def function(arg1,arg2,arg3):
  print(arg1)
  print(arg2)
  print(arg3)

x=['a','b','c']
y=('d','e','f')
z={'arg1':'g','arg2':'h','arg3':'i'}

function(*x)    # リスト
function(*y)    # タプル
function(*z)    # 辞書
function(**z)   # 辞書（辞書のキーと関数の引数名を一致させる）

a
b
c
d
e
f
arg1
arg2
arg3
g
h
i


## ファイルの読み書き

In [36]:
import sys
ROOT_PATH='data'
sys.path.append(ROOT_PATH)

### open()
* "r"は、ファイルを読み込み専用で開きます。
* "w"は、ファイルを書き出し専用で開きます。もし、すでにあるファイルパスを指定した場合、ファイルは上書きされます。ファイルがまだない場合、新しいファイルが作られます。
* "w+"は、読み書き両方できるようにファイルを開きます。これも、ファイルがすでにある場合は上書きします。ファイルが無ければ、新しいファイルを作って、読み書きします。
* 文字コードについて  
https://docs.python.org/ja/3/howto/unicode.html

In [37]:
st=open(ROOT_PATH+'/st.txt','w',encoding='utf-8')
st.write('Python!からこんにちは')
st.close()  # close()しないとファイルが閉じない

In [7]:
# ファイルを自動的に閉じる方法
with open(ROOT_PATH+'/st.txt','w') as f:
    f.write('Python!')

In [8]:
with open(ROOT_PATH+'/st.txt','r') as f:
    print(f.read())

Python!


In [9]:
my_list=[]

with open(ROOT_PATH+'/st.txt','r') as f:
    my_list.append(f.read())

print(my_list)

['Python!']


### CSVファイルの読み書き
CSVファイルを開くときもwith文を使えますが、csvモジュールを使ってファイルオブジェクトからcsvオブジェクトに変換するコードはwith文の内側で実行してください。

コーリー・アルソフ. 独学プログラマー Python言語の基本から仕事のやり方まで (Japanese Edition) (Kindle の位置No.1849-1851). Kindle 版. 

In [11]:
import csv

with open(ROOT_PATH+'/self_taught.csv','w',newline='') as f:
    w=csv.writer(f,delimiter=',')
    w.writerow(['one','two','four'])
    w.writerow(['three','five','six'])

In [13]:
import csv

with open(ROOT_PATH+'/self_taught.csv','r') as f:
    rows=csv.reader(f,delimiter=',')
    for row in rows:
        print(','.join(row))

one,two,four
three,five,six
