In [1]:
import statistics

In [2]:
import numpy as np

In [3]:
'''
statistics
.mean()

  機能：
    与えられた配列の平均値を返す
  使い方：
    statistics.mean(''配列)
'''
a=np.arange(10)
print(a)
print(statistics.mean(a))

[0 1 2 3 4 5 6 7 8 9]
4


In [5]:
'''
statistics
.median()

  機能：
    与えられた配列の中央値を返す
  使い方：
    statistics.median('配列')
'''
a=np.arange(10)
print(a)
print(statistics.median(a))

[0 1 2 3 4 5 6 7 8 9]
4.5


In [13]:
'''
statistics
.mode()

  機能：
    与えられた配列の最頻値を返す
  使い方：
    statistics.mode('配列')
'''
a=np.random.randint(0,10,10)
print(a)
print(statistics.mode(a))

[5 0 1 3 0 6 2 4 1 1]
1
